name: night-monitor CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker buildx build \
            --platform linux/arm64 \
            --push \
            -t "${{ secrets.DOCKERHUB_USERNAME }}/night-monitor:latest" \
            .

      - name: SSH into Gateway and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GATEWAY_IP }}
          username: ${{ secrets.GATEWAY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull "${{ secrets.DOCKERHUB_USERNAME }}"/night-monitor:latest
            docker-compose -f ~/night-monitor/docker-compose.yml down || true
            docker-compose -f ~/night-monitor/docker-compose.yml up -d